### PR TITLE
Bumped min .NET runtime version from 6.0.2 to 6.0.7

### PR DESCRIPTION
**Pull request by eraydin**

### CODE REVIEW

**Comment by caesay** [comment]
Hi, thanks for the PR - but can you please describe why this change was necessary? 

If Squirrel is installing dotnet, it will always install the latest minor version (eg. 6.0.7, 6.0.8, or beyond). In general, every minor version will be build compatible - so you can compile your app on any version of the 6.0 SDK and it will work on any 6.0 runtime. The minimum required version was bumped from 6.0.0 to 6.0.2 to workaround this behaviour because of a bug in the dotnet SDK that broke backwards compatibility. There is more info  about this bug in the link in the log message. This means dotnet will be upgraded if it is < 6.0.2, otherwise if >=6.0.2 is already installed, nothing will be done. 

Additionally, if your app requires a specific runtime, you can specify exactly what version your app needs by using the framework argument, eg. `-f net 6.0.6`.

**Comment by eraydin** [comment]
Hi @caesay,

I was a bit confused that it installs `.net6.0.2` as default instead of `.net6.0.latest` if the `--framework` parameter is set to `.net6.0`. And I did not know the reasoning behind that. Thanks a lot for the explanation. I am going to close this PR, and will set the minor version manually.

And, thanks a lot for this beautiful project!

**Comment by caesay** [comment]
It will always install the latest version. If that's what you want, then you should _not_ add the minor/patch value manually. `--framework net6.0` will always install the latest version, but will enforce that the system will _at least_ have 6.0.2 installed. 

Some examples:
- If dotnet 6.0 is not installed, then 6.0.latest will be installed.
- If 6.0.0 is already installed, then 6.0.latest will be installed. (because it is < 6.0.2, only done due to the linked bug)
- If 6.0.5 is installed, then nothing additional will be installed.

**Comment by eraydin** [comment]
You are 100% right. I just ran the installer on a freshly installed Windows VM, and can verify that yes it installs the latest version of .NET. Also, the code in `VersionInfo` class verifies it as well. Sorry for the noise!

But, I guess the .NET dependency warning message mislead me. That's the reason why I thought that it does not install the latest .NET. 

`YourAppName requires .NET 6.0.2 Desktop Runtime (x64) installed to continue, would you like to install it now?`

**Pull request closed without merging**
